# Generated by Django 6.0.2 on 2026-02-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technologies', models.CharField(blank=True, max_length=200)),
                ('project_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='portfolio_images/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Projekt portfolio',
                'verbose_name_plural': 'Projekty portfolio',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Wiadomość kontaktowa', 'verbose_name_plural': 'Wiadomości kontaktowe'},
        ),
    ]
