# Generated by Django 6.0.2 on 2026-02-26 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_portfolioproject_alter_contactmessage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('summary', 'Podsumowanie'), ('experience', 'Doświadczenie'), ('education', 'Wykształcenie'), ('skills', 'Umiejętności'), ('projects', 'Projekty'), ('certificates', 'Certyfikaty'), ('languages', 'Języki'), ('other', 'Inne')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sekcja CV',
                'verbose_name_plural': 'Sekcje CV',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('photo', models.ImageField(default='static/img/cv_img.png', upload_to='cv_photos/')),
            ],
            options={
                'verbose_name': 'Osoba CV',
                'verbose_name_plural': 'Osoby CV',
            },
        ),
        migrations.CreateModel(
            name='ExperienceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_items', to='pages.cvsection')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.AddField(
            model_name='cvsection',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.person'),
        ),
    ]
